- name: Authenticate and Import Azure Resource Manager Credentials in AAP
  hosts: localhost
  module_defaults:
    ansible.builtin.uri:
      validate_certs: false
  gather_facts: no

  vars_files:
    - subscriptions.yml  # Load subscription IDs from an external file
  vars:
    # AAP Controller URL
    aap_controller_url: "https://192.168.86.29:8443"

    # Base Credential parameters
    credential_name: "subscription id 1"
    credential_description: "Azure Resource Manager credential for AAP"
    organization_id: 3

    # Azure ARM Credentials
    azure_client_id: "39dc1694-c978-4611-8682-c8a71853b71e"
    azure_client_secret: "somekey"
    azure_tenant_id: "6dd8b6a1-6749-4de3-a27e-3fd3484c6da7"
    
  tasks:
    - name: Create Credential
      ansible.controller.credential:
        name: azure_credential1
        organization: "{{ organization_id }}"
        credential_type: "Microsoft Azure Resource Manager"
        state: present
        inputs:
          client: "{{ azure_client_id }}"
          secret: "{{ azure_client_secret }}"
          subscription: "12345"
          tenant: "{{ azure_tenant_id }}"
        controller_oauthtoken: ZDhlKIi7QWcOpjOPiARUuGzttoB18f
        controller_host: https://localhost:8443
        validate_certs: false
      register: create_credential_responses1
      delegate_to: localhost
            
    - name: Display results for each subscription
      debug:
        var: create_credential_responses1.results 
       
