- name: Authenticate and Import Azure Resource Manager Credentials in AAP
  hosts: localhost
  gather_facts: no

  vars_files:
    - subscriptions.yml  # Load subscription IDs from an external file


  vars:
    # AAP Controller URL
    aap_controller_url: "https://host1.example.com:8443"

    # Base Credential parameters
    credential_name: "subscription id 1"
    credential_description: "Azure Resource Manager credential for AAP"
    organization_id: 3

    # Azure ARM Credentials
    azure_client_id: "39dc1694-c978-4611-8682-c8a71853b71e"
    azure_client_secret: "somekey"
    azure_tenant_id: "6dd8b6a1-6749-4de3-a27e-3fd3484c6da7"
    controller_validate_certs: "{{ vault_controller_validate_certs | default(lookup('env', 'CONTROLLER_VERIFY_SSL')) }}"
  tasks:

    - name: Set API token as a variable
      set_fact:
        api_token: PYCNiXtSTxlstK9v3uOoCUOb3VszMN

    - name: Create Azure Credential for each Subscription ID in AAP Controller
      uri:
        url: "{{ aap_controller_url }}/api/v2/credentials/"
        method: POST
        headers:
          Authorization: "Bearer PYCNiXtSTxlstK9v3uOoCUOb3VszMN "
          Content-Type: "application/json"
        body_format: json
        body:
          name: "{{ credential_name }} - {{ item }}"
          description: "{{ credential_description }} for subscription {{ item }}"
          organization: "{{ organization_id }}"
          credential_type: 8  # Azure credential type ID
          validate_certs: no
          inputs:
            client: "{{ azure_client_id }}"
            secret: "{{ azure_client_secret }}"
            subscription: "{{ item }}"
            tenant: "{{ azure_tenant_id }}"
        status_code: 201
      loop: "{{ subscriptions }}"
      register: create_credential_responses

    - name: Display results for each subscription
      debug:
        var: create_credential_responses.results 
       
