---
- name: Authenticate and Import Azure Resource Manager Credentials in AAP
  hosts: localhost
  gather_facts: no
  vars_files:
    - subscriptions.yml  # Load subscription IDs from an external file
  vars:
    # AAP Controller URL and organization
    aap_controller_url: "https://localhost:8443"
    organization_id: "Org1"

    # Azure ARM Credentials
    azure_client_id: "12345"
    azure_client_secret: "{{ secret_key }}"   # template's survey provided value
    azure_tenant_id: "12345"

  tasks:
    - name: Obtain API token from AAP Controller
      uri:
        url: "{{ aap_controller_url }}/api/v2/tokens/"
        method: POST
        user: "{{ aap_username }}"             # template's survey provided value
        password: "{{ aap_password }}"         # template's survey provided value
        force_basic_auth: yes
        status_code: 201
        headers:
          Content-Type: "application/json"
        body_format: json
        body: {}
      register: auth_token_response

    
    - name: Display results for each subscription
      debug:
        var: create_credential_responses.results
